[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rdev = "0.5.3"

# 必须使用 0.2.x 或 0.3.x 版本（基于新版 API）。
# 如果误用了老的 0.1.x 版本，Enigo 的初始化和按键语法完全不同
enigo = { version = "0.3.0", features = ["serde"] }
# 懒加载状态库
lazy_static = "1.5.0"

# rdev = "0.5"       # 跨平台全局输入
tokio = "1.0"      # 异步监听
